#!/bin/sh

IMAGE_NAME="${IMAGE_NAME:-ghcr.io/wesley-dean/jinja2-cli}"

directory="${directory:-$(pwd)}"
user="${user:-$(id -u)}"

docker run --rm -it -v "${directory}:${directory}" -w "${directory}" -u "${user}" "${IMAGE_NAME}" "$@"
