---
name: Publish

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  workflow_dispatch:

permissions: read-all

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v3

      - name: Build and Publish Image
        uses: wesley-dean/publish_container@v1.0.1
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_PAT }}
          github_ref: ${{ github.ref }}
          repository_name: ${{ github.event.repository.name }}
